### ISSUE TITLE
en los datos de id_study y id_com credos, me muestra fechas incorrectas

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#100]
Las fechas son siempre años, peor en pocasiones me muetra meses + años

**Comment by VeruGHub** [comment]
Te refieres a study_year? a mi me salen años entre 1972 y 2016 pero nada más

**Comment by davidperezmartorell** [comment]
esto fueron errores de importacion al pasar a travs de excel. resuelto
