### ISSUE TITLE
cuando unifica la coordenadas

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#107]
@VeruGHub 

Creo que el unico sitio donde unificamos las coordenadas es aqui
  map <- map %>%
    setView(lng = mean(inputData2$exact_long, na.rm = TRUE), 
            lat = mean(inputData2$exact_lat, na.rm = TRUE), 
            zoom = 3)

Esto es en el programa renderMap
https://github.com/davidperezmartorell/forestMap/blob/a8c2d8d03cdc440fef39f832837e1ed2d711204d/renderMap.R#L145

esto creo que ya no es necesraio porque tras los varios ciclos de mejoras, ahora nos dimos cuenta que estamos representando los id_study, no los id_comm y hemos quitado stge y disturbance1_age_clean incorporando esta nueva variable

        possible_alternatives == "recovering" ~ "green",
        possible_alternatives == "reference, recovering" ~ "orange",
        possible_alternatives == "recovering, disturbed" ~ "purple",
        possible_alternatives == "reference, recovering, disturbed" ~ "brown"
        
        Como para cada id_study tendremos un único valor, no hace falta que busquemos ese mean de lat and lon
        
        en las siguientes versiones, omitiré estos comandos que hacen el mean
        
        en cuanto leas esto, si estas de acuerdo, puedes cerrar el issue

**Comment by davidperezmartorell** [comment]
NONONO, no es esto, sigo buscando donde hacemos media en algun lado.
por ahora no lo he encontrado.
solo he encontrado una transformación de char a numeric y que no necesito omitir los values NA para los valores que tengo que son unicos para cada id_study.


esto que te mostraba era para plotear el mapa, necesita saber que pantalla inicial debe tomar y hace un summary de lat y lon, le pone un zoom y ahi esgoge si el zoom inicial es muy cercano o lejano y donde esta su centro.

**Comment by davidperezmartorell** [comment]
mira, encontré esto en una version anterior
  # Calculate centroid for each country
  centroid_data <- summary_data %>%
    group_by(Country) %>%
    summarise(
      centroid_lat = mean(exact_lat),
      centroid_long = mean(exact_long),
      total_count_study = sum(count_study),
      total_count_comm = sum(count_comm),
      .groups = 'drop'
    ) %>%
    ungroup()

esto lo hacia en su momento, pero ya lo quité. esto es viejo (2 meses)

**Comment by VeruGHub** [comment]
David, si ya no usas ese dataset donde cambiaste "a mano" las coordenadas (como me dices aquí: https://github.com/davidperezmartorell/forestMap/issues/93), olvidate de esto. 
Entiendo que para cada estudio haces una media de las coordenadas de las comunidades en algún sitio del script y esta media es con lo que representas los puntos. 
Para terminar de confirmar que está bien, dime porfi que input data usas aqui:
https://github.com/davidperezmartorell/forestMap/blob/a8c2d8d03cdc440fef39f832837e1ed2d711204d/renderMap.R#L23

**Comment by davidperezmartorell** [comment]
esta funcion es llamada desde el programa principal app.R para representar el mapa

https://github.com/davidperezmartorell/forestMap/blob/a8c2d8d03cdc440fef39f832837e1ed2d711204d/app.R#L331

le envía assembleages_filtered que es una agrupación de datos que lo hace al principio aqui en app.R

https://github.com/davidperezmartorell/forestMap/blob/a8c2d8d03cdc440fef39f832837e1ed2d711204d/app.R#L51

**Comment by VeruGHub** [comment]
Viendo estos scripts, yo diría que te tendría que coger una coordenada por cada comunidad. Como assemblages_filtered tiene "id_comm" que es único para cada fila, cuando aplicas la función unique() se queda con el mismo número de filas. Es decir, que las comunidades que tienen coordenadas unicas se quedarían como filas por separado y las que tienen una coordenada común también. 
Sin embargo, luego ves el mapa y hay un punto por estudio. También en casos donde cada comunidad tiene una coordenada diferente (p.e Zhu et al 2009 en China tiene 3 puntos porque tiene 3 estudios, pero 27 comunidades cada una con unas coordenadas).
Así que no sé que estará pasando... pero bueno, parece que está bien representado y a mi me daba miedo que hubieras metido coordenadas a mano cuando no podías leer bien los archivos

**Comment by davidperezmartorell** [comment]
como al final escogemos un unico estudio porque no podemos mostrar los datos de measurement y taxon que son de estudios o comunidades, puedo mostrarlo en un único punto.
Cuando te acercas con zoom se separan un poco de forma predefinida por leaflet
