### ISSUE TITLE
Etiquetas de cada estudio

### ISSUE THREAD

**Issue by VeruGHub** [davidperezmartorell/forestMap#108]
Otra cosa que se me olvidó comentarte ayer y que no te llevará mucho (creo). Ahora cuando haces click en un estudio aparece un bocadillo con la siguiente información:

Country: China
Year of study: 2004
Name of Study group: RU_Zhu 2009_Shrub
Number of studies: 1
Stage: recovering
Study Common Taxon Clean: shrubs

Number of studies no sé que es y stage ya hemos dicho que no tiene sentido porque hay varios stages en cada estudio y ya lo vamos a poner por colores. Lo dejaría así:

Country: China
Year of study: 2004
Number of assemblages: [en la base de datos de assemblages es la columna n_comm_available]
Common taxon: shrubs
Metric: [en la base de datos de assemblages es la columna metric]
Source: Zhu 2009 [en la base de datos de assemblages es la columna citation]
Origin database: RU [en la base de datos de assemblages es la columna database]

Ya me dirás como lo ves

**Comment by davidperezmartorell** [comment]
agregado
