### ISSUE TITLE
[corregido]mas errores en id_study

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#116]
Hola, al cargar los datos y compaar los id_study, me encuentor lo siguiente

caso Lopez Quintero
en taxon
id_sdudy -> PR_Lopez-Quintero et al. 2012_Plants_Lopez_CA;
En assembleages -> PR_Lopez-Quintero et al. 2012_Plants_Lopez

Solucion:Lo modifico a mano en el csv origen que me enviaste

caso Liebsch
En taxon id_study es CU_Liebsch et al. 2008, Liebsch et al. 2007_Guapyassu 1994
En assembleages -> ;CU_Liebsch et al. 2008, Liebsch et al. 2007_Guapyassu 1994;

Le agrego la coma en taxon

Ya se puede cerrar el ticket, solo es informativo. Creo quye el de Liebsch lo modifiqué yo en assembleages porque la , me molestaba en su momento cuando separaba por ",", pero ahora que ya no trabajo con excel (casi), me da igual que esté o no.
Ahora trabajo mas con R y notepad por si tengo que consultar algo. Ele xcel solo lo he usado para el citation y porque lo trabajé bastante a mano.

**Comment by VeruGHub** [comment]
Hola! De acuerdo con lo de la coma que no cuadra. En cuanto a Lopez Quintero, debería ahora haber dos estudios diferentes en ambos archivos: uno que acaba en Plants_Lopez y otro que acaba en Plants_Lopez_CA. Porfi, compruebalo y si no es así avisame

**Comment by davidperezmartorell** [comment]
ya cuadra todo. Ya no hay diferencias de estudios entre taxon y assembleages
