### ISSUE TITLE
modificar los rangos de fecha

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#138]
Ladivisipon de fehas que tenia yo era la siguiente
mutate(age_group = cut(age, breaks = c(0,5,10,15,20,25,30,35,40,45,50,75,100,200,300,400,500), include.lowest = TRUE))
y se desea modificar a esta

mutate(age_group = cut(age, breaks = c(0,10,20,30,40,50,60,70,80,90,100,500), include.lowest = TRUE))
voy a mostrar los resultados

**Comment by davidperezmartorell** [comment]
veo los datos igual, quizas con el segundo patrón hay ciertos huecos en el rango 80-90
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/ab5c50b7-eef1-4649-af87-c18b81729b50)

que hago, lo dejo como antes, modifico?
lo tengo como comentario en el código, se facil dar marcha atras


    #mutate(age_group = cut(age, breaks = c(0,5,10,15,20,25,30,35,40,45,50,75,100,200,300,400,500), include.lowest = TRUE))
    mutate(age_group = cut(age, breaks = c(0,10,20,30,40,50,60,70,80,90,100,500), include.lowest = TRUE))

**Comment by Julenasti** [comment]
A mi independientemente del patrón me parece más coherente mostrar los resultados siempre con el mismo intervalo, excepto para valores muy elevados donde tienes pocos datos, por lo que me decantaría por la nueva opción. Quizás se podría seguir con el intervalo de 10 hasta 150? pero creo que dijisteis que para valores superiores a 100 hay pocos datos. Si es así lo dejaría tal como está

**Comment by davidperezmartorell** [comment]
es facil probar.lo dibujo y de lo pongo aqui a ver que ocurre...pero creo que encontraremos poca cosa. eso si, todos los gráficos de la misma pestaña tendrán losmismos inervalos, eso si, of course

**Comment by davidperezmartorell** [comment]
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/17b572d6-ded6-4f32-b860-eb45456c0abe)

**Comment by Julenasti** [comment]
Puede que sean demasiados breaks? Quizás con el del medio puede ser suficiente pero haría que los boxplots no estuvieran uno encima del otro, es decir, como en la gráfica de la derecha

**Comment by davidperezmartorell** [comment]
sisi, sin overlap.
aqui esta. los datos son los itnermedios. 0,10,20,30,40,50,60,70,80,90,100,500.
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/6d9dea1a-fecc-44b8-a0e7-4314c09937e2)
cierro el caso

**Comment by VeruGHub** [comment]
Perfecto, mejor con la división de intervalos intermedios. Tenemos que mirar el próximo día las clasificaciones en tipos de perturbación (grafico 2) y de taxones (grafico 3)!
