### ISSUE TITLE
valores de presencia/ausencia por orden/fenero y familia

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#141]
Os acordais que dijimos que tendriamos que plotear para cada estudio en lugar de las medianas de los valores de las familias, que salian repetidos, intentar calcular la presencia/ausencia de valores diferentes a 0 para cada familia/genero/orden?
Parecía complicado, pero en realidad es hacer groups simplemente. He almacenado los 3 tipos de datos para todos lose studios en 3 archivos y los filtro aun mas al hacer click.
Los círculos son gordotes, pero sew pueden poner par que almenos no se pisen. Solo que cuando lo valores son pequeños, queda un pco ridiculillo :-D
decidme que os parece.
Por cierto, ya acabé todas las tareas. Voy a subirlo. En el programa gratuito de shiny, solo soporta 1GB y peta, a ve ahora que uso menos gráficos

Los resultados los puse en burbujas, a ver que os parece
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/d8b4f0b9-855e-492a-b814-c5a53fe3b17f)
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/d1876f7d-b64a-4268-92a6-af8df1f69a01)
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/cecf87a5-ece9-4872-884f-71bc0507134d)

**Comment by davidperezmartorell** [comment]
aqui esta el progama por si quereis mirarlo on line
https://qm0lyl-david-perez0martorell.shinyapps.io/forestmap/

**Comment by Julenasti** [comment]
el tamaño de los circulos indica el número de presencias? Yo tenía en mente un connected scatterplot https://r-graph-gallery.com/connected_scatterplot_ggplot2.html
creo que puede quedar más claro

**Comment by davidperezmartorell** [comment]
lo que ocurre es que se montan puntos uno sobre otro y como no tienen presencia constante, desaparecen.
Este es un ejemplo de lo que ocurre
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/1e9fa048-4197-48a6-91f1-c2741577ca93)
Esto ocurre porque en este gráfico mostramos la mediana y como en este caso, no es un valor de medida sino presencia/ausencia,  done conté si sta la clase|familia|orden o no.Parece que los valores son iguales.
Por eso lo puse uno bajo el otro con esos círculos.

**Comment by VeruGHub** [comment]
Genial lo de las agrupaciones por orden, familia, etc. 
A mi también me gusta más también el tipo de gráfico que dice Julen, donde el eje Y sea la cantidad de taxones en cada orden/familia/clase (o la mediana si hay varios plots por edad). Es raro lo que te sale en último gráfico que mandas, David, porque para Liliopsida te debería salir algún punto al menos para 68 y 200 años. Como se ve en el gráfico de arriba tienes algunos taxones en esa clase, pero menos que en Magnoliopsida por lo que los puntos y las líneas no deberían superponerse.
Además, cuando tienes tantos ordenes y familias, representaría como mucho los 10 más abundantes porque si no es un lio con tantos colores.

**Comment by davidperezmartorell** [comment]
modificado a lineas y puntos
