### ISSUE TITLE
crear index y búsqueda de repetidos

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#35]
Hola. Al crear el indice, veo que id no esta en taxon, asi que creo que debemos comparar y hacer un índice de campo id_study.
He mirado las diferencias entre ambos documentos y veo diferencias
¿Que sugieres con estos?

**Valores id_study que si estan en taxon y no estan en assembleages**
1                          PR_Katovai et al. 2012_Understory plants; Solomon Islands
2                                          PR_Lopez-Quintero et al. 2012_Fungi_Lopez
3                                             PR_Noske et al. 2008_Epiphytes Ecuador
4                                     CU_Abbot et al. 2003_1 1A Cockroaches trapping
5                                    CU_Abbot et al. 2003_1 1A Grasshoppers trapping
6                           CU_Abbot et al. 2003_1 1A Spiders and relatives trapping
7             CU_Aerts et al. 2008_1 2R Birds visual observation (transect or point)
8                            CU_Andrade & Rubio-Torgler 1994_1 1A Birds mist netting
9                                     CU_Barlow et al. 2007a_1 1A Birds mist netting
10          CU_Barlow et al. 2007a_1 1A Birds visual observation (transect or point)
11                  CU_Barlow et al. 2007b_1 1A Butterflies (fruit-feeding) trapping
12  CU_Bihn et al. 2008_1 2R Ants; litter (genera richness) random plots or quadrats
13                                     CU_Bobo et al. 2006_1 1A Butterflies trapping
14 CU_Estrada et al. 1994_1 1A NVSM visual observation (transect or point); trapping
15    CU_Gillison et al. 2003_1 1A Termites systematic searching (transect or point)
16                        CU_Liebsch et al. 2008; Liebsch et al. 2007_Guapyassu 1994
17                         CU_Stark et al. 2006_1 2R Plants random plots or quadrats
18                                                          RU_Itioka 2015_Butterfly
19                                                    RU_Zhu 2010_Soil actinomycetes
20                                                         RU_Zhu 2010_Soil bacteria
21                                                            RU_Zhu 2010_Soil fungi
22                                                  RU_Hopp 2010_Bettle in cambisols
23                                                   RU_Hopp 2010_Bettle in gleysols
24                  RU_Negrete-Yankelevich 2007_Soil macroinvertebrates below litter
25                     RU_Negrete-Yankelevich 2007_Soil macroinvertebrates in litter
26                                                RU_Redi 2005_Millipede spontaneous
27                                                       RU_Maeto 2004_Ant secondary
28                                                         RU_Ashwood 2019_Earthworm
29                                                          RU_Ramos-Fabiel 2018_Bee
30                                                     RU_Tausan 2017_Ant (Chrono 1)
31                                                     RU_Tausan 2017_Ant (Chrono 2)
> anti_join(index_assembleages,index_taxon, by = "id_study")

**Valores id_study que si estan en assembleages y no estan en taxon**
1        PR_Katovai et al. 2012_Understory plants, Solomon Islands
2                    PR_Lopez-Quintero et al. 2012_Plants_Lopez_CA
3                          PR_Noeske et al. 2008_Epiphytes Ecuador
4       CU_Liebsch et al. 2008, Liebsch et al. 2007_Guapyassu 1994
5  CU_Stark et al. 2006_1 2R Plants random plots or quadrats_age 5
6  CU_Stark et al. 2006_1 2R Plants random plots or quadrats_age 1
7 CU_Stark et al. 2006_1 2R Plants random plots or quadrats_age 10

**Comment by VeruGHub** [comment]
Hola David:
Gracias por checkear esto. Tienes razón que "id" no está en la tabla taxon. Como columna de comparación valdría también el "id_comm" (que representa una única fila en assemblage y y varias en taxon), pero bueno, da igual porque con "id_sudy" ya sirve para este filtro. 
Respeto a los valores de id_study que están en taxon y no en assemblage, hay que descartarlos por ahora. Como verás en los nombres, son estudios que no son de plantas y tengo los datos extraidos a nivel de taxon, pero no a nivel de assemblage. 
Respecto a los 7 valores de id_study que si estan en assemblages y no están en taxon, tengo que ver que pasa porque deberían coincidir todos. Por ejemplo, en Katovai et al, veo que es una cuestión de que en assemblage hay una "," y en taxon un ";". Voy a repasarlo y te paso las tablas arregladas. Tu de momento para seguir trabajando filtra también estos casos, pero más adelante no hará falta el filtro.
Vero

**Comment by davidperezmartorell** [comment]
dejo esto pendiente a lo que me digas. Por ahora descarto los datos. Ahora abro otro issue con otra duda acerca este índice que estoy creando.

**Comment by davidperezmartorell** [comment]
cierro este issue

**Comment by davidperezmartorell** [comment]
en su momento ,creaba una tabla index que era la union de assembleages y taxon para extraer los esdutios que estaban en ambos.
me encontré casos que solo estaban en uno o otro sitio y no se que hacer con ellos.
luego me di cuenta que ese index no lo necesito porque solo me hacia perder tiempo para un index que no usba, pero la diferencia de estudios sigue ahi.
no me impacta en el resultado, en un principio, menos si me enfoco solo a Calvino... y dems, en general extrago datos o de asssembleages o de taxon, al mismo tiempo lo hago poco.
Solo era para informarte.

**Comment by davidperezmartorell** [comment]
ahora los datos que estan en assembleages y no estan en taxon. Lo creo a traves de este codigo que esta dentro de loadData.R
https://github.com/davidperezmartorell/forestMap/blob/a8c2d8d03cdc440fef39f832837e1ed2d711204d/loadData.R#L31C4-L33C104

**Comment by davidperezmartorell** [comment]
Para PR_Lopez-Quintero et al. 2012_Plants_Lopez_CA, busco info en ambos dataframes
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/64418619-aa87-4db8-933c-6734a7bad030)

Como vemos, taxon solo contiene "PR_Lopez-Quintero et al. 2012_Plants_Lopez", pero assembleages tiene _CA en el final de id_Study
Como los datos ya estan diferenciados por site que viene de assembleages, voy a quitar este _CA que esta en assembleages.

**Comment by davidperezmartorell** [comment]
caso CU_Gillison et al. 2003_2 3I Plants random plots or quadrats
No hay referencias en taxon de este estudio. Lo marco para borrar datos de assembleages en la carga
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/5ceed444-4b91-4035-8771-0e98cba45c7c)

**Comment by davidperezmartorell** [comment]
caso "inclusion of the area on a reserve since 1976"
Esto en realidad, noe s un estudio, son unas lineas que al importar los datos los ha recibido como error.
Al importar los datos de CU_Grau et al. 1997_1 1A Trees (10 cm dbh) random plots or quadrats, parece que el campo "historic_impact", carga solo una parte del texto
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/ec5445f0-b693-4566-a492-2471f968bad7)

y el resto lo considera como si hubiera un separador y lo agrega en otra linea dejando "inclusion of the area on a reserve since 1976" como si fuera el primer campo, o sea el id_study de otra linea

CU_Grau et al. 1997_1 1A Trees (>10 cm dbh) random plots or quadrats_OG_1 (f5)_NA;CU;Grau et al. 1997_1 1A Trees (10 cm dbh) random plots or quadrats_OG_1 (f5)_NA;CU_Grau et al. 1997_1 1A Trees (10 cm dbh) random plots or quadrats;CU_Grau et al. 1997_1 1A Trees (>10 cm dbh) random plots or quadrats;Grau et al. 1997;1 1A Trees (>10 cm dbh) random plots or quadrats;OG_1 (f5);NA;f5;-26.8;-65.38;500;Old;1996;category;reference;Trees;Trees (>10 cm dbh);abundance;density (trees/ha);yes;random plots or quadrats;1;NA;25;6;10000;A large percentage of the area was deforested during the first half of this century, and planted with annual crops and fruit orchards, mostly citrus. As a
consequence of soil fertility loss, lands were abandoned and progressivety revegetated. The inclusion of the area on the reserve since 1976 enhanced forest recovery processes.;NA;;inclusion of the area on a reserve since 1976;0;none;NA;NA;Argentina;trees;engineers;none;protection;NA;none;none;0;1;none;protection;study;species;37;18;213;3.45189863651903;1160.450249;10;0;-26.8;-65.38
CU_Grau et al. 1997_1 1A Trees (>10 cm dbh) random plots or quadrats_f1_NA;CU;Grau et al. 1997_1 1A Trees (10 cm dbh) random plots or quadrats_f1_NA;CU_Grau et al. 1997_1 1A Trees (10 cm dbh) random plots or quadrats;CU_Grau et al. 1997_1 1A Trees (>10 cm dbh) random plots or quadrats;Grau et al. 1997;1 1A Trees (>10 cm dbh) random plots or quadrats;f1;NA;f1;-26.8;-65.38;11.5;11-12;1996;mean;recovering;Trees;Trees (>10 cm dbh);abundance;density (trees/ha);yes;random plots or quadrats;1;NA;25;6;10000;A large percentage of the area was deforested during the first half of this century, and planted with annual crops and fruit orchards, mostly citrus. As a
consequence of soil fertility loss, lands were abandoned and progressivety revegetated. The inclusion of the area on the reserve since 1976 enhanced forest recovery processes.;NA;;inclusion of the area on a reserve since 1976;1;none;NA;NA;Argentina;trees;engineers;cultivation;protection;NA;none;none;0;1;none;protection;study;species;37;8;596;0.706729221991972;254.222006;3;0;-26.8;-65.38
CU_Grau et al. 1997_1 1A Trees (>10 cm dbh) random plots or quadrats_f2_NA;CU;Grau et al. 1997_1 1A Trees (10 cm dbh) random plots or quadrats_f2_NA;CU_Grau et al. 1997_1 1A Trees (10 cm dbh) random plots or quadrats;CU_Grau et al. 1997_1 1A Trees (>10 cm dbh) random plots or quadrats;Grau et al. 1997;1 1A Trees (>10 cm dbh) random plots or quadrats;f2;NA;f2;-26.8;-65.38;22.5;20-25;1996;mean;recovering;Trees;Trees (>10 cm dbh);abundance;density (trees/ha);yes;random plots or quadrats;1;NA;25;6;10000;A large percentage of the area was deforested during the first half of this century, and planted with annual crops and fruit orchards, mostly citrus. As a
consequence of soil fertility loss, lands were abandoned and progressivety revegetated. The inclusion of the area on the reserve since 1976 enhanced forest recovery processes.;NA;;inclusion of the area on a reserve since 1976;1;none;NA;NA;Argentina;trees;engineers;cultivation;protection;NA;none;none;0;1;none;protection;study;species;37;21;365;2.85369452331019;692.161096;8;0;-26.8;-65.38
CU_Grau et al. 1997_1 1A Trees (>10 cm dbh) random plots or quadrats_f3_NA;CU;Grau et al. 1997_1 1A Trees (10 cm dbh) random plots or quadrats_f3_NA;CU_Grau et al. 1997_1 1A Trees (10 cm dbh) random plots or quadrats;CU_Grau et al. 1997_1 1A Trees (>10 cm dbh) random plots or quadrats;Grau et al. 1997;1 1A Trees (>10 cm dbh) random plots or quadrats;f3;NA;f3;-26.8;-65.38;47.5;45-50;1996;mean;recovering;Trees;Trees (>10 cm dbh);abundance;density (trees/ha);yes;random plots or quadrats;1;NA;25;6;10000;A large percentage of the area was deforested during the first half of this century, and planted with annual crops and fruit orchards, mostly citrus. As a
consequence of soil fertility loss, lands were abandoned and progressivety revegetated. The inclusion of the area on the reserve since 1976 enhanced forest recovery processes.;NA;;inclusion of the area on a reserve since 1976;1;none;NA;NA;Argentina;trees;engineers;cultivation;protection;NA;none;none;0;1;none;protection;study;species;37;20;338;3.48052388566412;884.46513;8;0;-26.8;-65.38
CU_Grau et al. 1997_1 1A Trees (>10 cm dbh) random plots or quadrats_f4_NA;CU;Grau et al. 1997_1 1A Trees (10 cm dbh) random plots or quadrats_f4_NA;CU_Grau et al. 1997_1 1A Trees (10 cm dbh) random plots or quadrats;CU_Grau et al. 1997_1 1A Trees (>10 cm dbh) random plots or quadrats;Grau et al. 1997;1 1A Trees (>10 cm dbh) random plots or quadrats;f4;NA;f4;-26.8;-65.38;47.5;45-50;1996;mean;recovering;Trees;Trees (>10 cm dbh);abundance;density (trees/ha);yes;random plots or quadrats;1;NA;25;6;10000;A large percentage of the area was deforested during the first half of this century, and planted with annual crops and fruit orchards, mostly citrus. As a
consequence of soil fertility loss, lands were abandoned and progressivety revegetated. The inclusion of the area on the reserve since 1976 enhanced forest recovery processes.;NA;;inclusion of the area on a reserve since 1976;1;none;NA;NA;Argentina;trees;engineers;cultivation;protection;NA;none;none;0;1;none;protection;study;species;37;21;357;3.1629945417057;979.452395;9;0;-26.8;-65.38

Como la definición "A large percentage of the area was deforested during the first half of this century, and planted with annual crops and fruit orchards, mostly citrus. As a consequence of soil fertility loss, lands were abandoned and progressivety revegetated. The inclusion of the area on the reserve since 1976 enhanced forest recovery processes." es muy larga, causa que se corte elo contenido. 
Las soluciones en R parece que es un trabajo individual para este contenido. Como es demasiado explicito, prefiero modificar la fuente reduciendo el contenido de una variable que no es tan principal. Omito este fragmento "The inclusion of the area on the reserve since 1976 enhanced forest recovery processes."

**Comment by davidperezmartorell** [comment]
caso CU_Li et al. 2011_1 2R Lichen random plots or quadrats
no existe  nada similar en taxon. lo quito de assembleages desde loadData.R
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/ff528d13-0bfe-443c-8fdc-7ad6a9583114)

**Comment by davidperezmartorell** [comment]
4   CU_Stark et al. 2006_1 2R Plants random plots or quadrats_age 5
5   CU_Stark et al. 2006_1 2R Plants random plots or quadrats_age 1
6  CU_Stark et al. 2006_1 2R Plants random plots or quadrats_age 10

En Taxon no hay referencias de Stark ni en id_study ni en id_comm. Lo borro de assembleages
> taxon[grepl("2006_1 2R", taxon$id_study), ] %>% select(id_study, id_comm) %>% unique()
[1] id_study id_comm 
<0 rows> (or 0-length row.names)

> taxon[grepl("Stark", taxon$id_study), ] %>% select(id_study, id_comm) %>% unique()
[1] id_study id_comm 
<0 rows> (or 0-length row.names)

> taxon[grepl("Stark", taxon$id_comm), ] %>% select(id_study, id_comm) %>% unique()
[1] id_study id_comm 
<0 rows> (or 0-length row.names)

> taxon[grepl("2006_1 2R", taxon$id_comm), ] %>% select(id_study, id_comm) %>% unique()
[1] id_study id_comm 
<0 rows> (or 0-length row.names)

**Comment by davidperezmartorell** [comment]
caso de "inclusion of the area on a reserve since 1976"

En una linea habia un salto de linea dividió el contenido en 2 lineas como si fueran 2 id_sduty. Lo interpretaba como un nuevo registro.
Elimino el salto y se adhiere al registro anterior sin dividirse

**Comment by davidperezmartorell** [comment]
El caso 25 , no tiene contenido.
Esto es porque en assembleages habia una linea vacia al final del archivo y lo interpretaba como un registro nuevo.
consideraba el id_study como un valor vacio y al compararlo con taxon encontraba diferencias.
Borrado el salto de linea al final del archivo.

**Comment by davidperezmartorell** [comment]
Ya no hay diferencias de id_study entre los dos archivos

**Comment by davidperezmartorell** [comment]
ya se puede cerrar esto. lo comentaré en la siguiente reunión y se puede cerrar

**Comment by davidperezmartorell** [comment]
al final, los errores que aun continuan son
Datos que estan en taxon y no estan en assembleages
1. "RU_Negrete-Yankelevich 2007_Soil macroinvertebrates below litter"
2. "RU_Negrete-Yankelevich 2007_Soil macroinvertebrates in litter"

Datos que estan en assembleages y no estan en taxon
1. CU_Gillison et al. 2003_2 3I Plants random plots or quadrats"
2. "CU_Li et al. 2011_1 2R Lichen random plots or quadrats"
3. "CU_Stark et al. 2006_1 2R Plants random plots or quadrats_age 5"
4. "CU_Stark et al. 2006_1 2R Plants random plots or quadrats_age 1"
5. "CU_Stark et al. 2006_1 2R Plants random plots or quadrats_age 10"

**Comment by davidperezmartorell** [comment]
se comentan difrencias en reunión. se envía resumen para ver porque hay estos errrores. Quizas faltan datos en taxon

**Comment by VeruGHub** [comment]
Respecto a los estudios (id_study) que no cuadran entre ambas tablas:
- Negrete-Yankelevich como dices es de macroinvertebrados y hay que filtrarlo de taxon.
- Gillison y Li: yo los tengo en ambas tablas en mis bases de datos. No sé que ha podido pasar, pero puede ser problema de las comas y puntos y comas.
- Stark: el id_study de la tabla taxon estaba mal. Lo he corregido.
- Lopez-Quintero: hay una parte de los registros en taxon donde el id_study tiene que contener _CA y otra que no. Son dos estudios diferentes dentro de la misma citation. Lo he corregido

Te adjunto unas tablas nuevas donde están corregido:
En taxon, el id_study de Noske, de Stark y de Lopez-Quintero
Ya no aparecen en ninguna tabla registros que no sean de plantas o líquenes.


Te recomiendo que para cargar los datos uses el siguiente script para evitar errores con comas y puntos y comas:
```
library(tidyverse)
com <- read_delim("assemblages.csv", delim = ";")
taxon <- read_delim("taxon.csv", delim = ";")
```

También en estas nuevas tablas los taxones están bastante corregidos, porque yo aquí ya incorporé todo el trabajo que hiciste con taxon_clean, pero si quieres volver a correr lo que chequeaste aquí por mi guay: https://github.com/davidperezmartorell/forestMap/issues/89. Eso sí, no hace falta que vuelvas a descargar de gbif la familia, orden, clase, etc, porque eso ya lo tienes.
[Uploading assemblages_david_app.csv…]()

**Comment by davidperezmartorell** [comment]
corregido. al final, como resumen, vemos que no es necesario index porque cargamos los datos d archivo. no es tan dinamico como para tener valores en una tabla index con claves primarias y demas.
