### ISSUE TITLE
Comparto el texto del TFM

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#36]
Hola, os comparto el texto del TFM que inicié en Septiembre recopilando info que iba tomando sin ningun objetivo claro, pero para ponerme al dia.
https://universidaddealcala-my.sharepoint.com/:w:/r/personal/david_perezm_edu_uah_es/Documents/ForestAssembly%20a%20global%20dataset%20of%20forest%20species%20assemblage.docx?d=w859961d7b47a4566ba7bbffbfbba0f03&csf=1&web=1&e=pA4LLm

¿Tenemos algun formato de TFM para presentar proyectos informáticos para biología?

**Comment by VeruGHub** [comment]
Hola:

En [este documento](https://masterrestecos.web.uah.es/DOC/Reglamento_unificado_MURestauraci%C3%B3n%20Ecosistemas%2090%20cr_final.docx) de la web del máster tienes toda la información de como hacer un TFM para el máster de restauración. Tu TFM cae dentro del tipo "técnico", pero no creo que nadie haya hecho hasta ahora una herramienta para visualizar datos así que tendrás que adaptar unpoco los contenidos que piden. Para ver como se presenta una app, echa un ojo al artículo que te envía Julen o también a este otro: https://www.mdpi.com/1999-4907/12/10/1405. 

Piensa que al menos tendrás que incluir algo de la situación actual de los bosques y su restauración y una justificación de por qué se necesita esta herramienta, una pequeña revisión de otras herramientas parecidas, la justificación técnica del diseño, y la presentación de la funcionalidad de la herramienta. Tendremos que ser listos con la justificación de la necesidad porque puede que por no ser algo habitual guste mucho o, por otra parte, también puede que no se entienda bien el TFM que se plantea.

No tengo acceso al enlace que envías de tu TFM. ¿Está también en el google drive que teníamos?

**Comment by davidperezmartorell** [comment]
el documento esta aqui, el el drive de la universidad

https://universidaddealcala-my.sharepoint.com/:w:/g/personal/david_perezm_edu_uah_es/EddhmYV6tGZFunu_-_u6DwMBrcSza2MoURSDmYjPs5hzzg?e=AnVdWX

lo pongo aqui porque tengo el Word que me da mas herramientas que el google docs
Miraré la docu que me dices. Dejo este issu abierto como tarea, porque ahora las gestiono desde aqui en lugr de la otra herramienta de gestión de tareas (Jira)

**Comment by VeruGHub** [comment]
Vale, sin problema. Esque no me deja acceder. Te he pedido acceso con mi correo de la UAH :)

**Comment by Julenasti** [comment]
Sí a mi tampoco me deja y te he solicitado acceso

**Comment by davidperezmartorell** [comment]
compartido, lo trabajos por ahi. ire abriendo tareas segun vayamos viendo
