### ISSUE TITLE
como mergea los datos index

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#37]
Hola, hasta ahora, mi idea era tomar los valores que nos interesan de taxon, los de assembleages y unirlo en un index para poder trabajar mejor , pero me encuentor lo siguiente.
1 Creo una lista con valores unicos de taxon con id_study unicos(esto ya trae debate porque se pueden escoger los unicos solo para id_study o la combinacion con id_com, taxon...), pero cojo solo id_study
2 Por otro lado una seleccion de los campos que me nteresan de assembleages, id_study, algunos valores que no interesan que son lo mas importante y agrego pais, geometria, ISO3.

Lo que ocurre es que para cada id_study (son mas de 1000), le multiplica las lineas de cada valor de assembleages creaeando una tabla d hasta 6GB. Esto esta combinando mal y estrujando las neuronas, me doy cuenta que no hace falta ese merge ni join. Os propongo
**Mi propuesta**
1 index -> Crear un índice con los valores id_study de taxon que tambien esten en assembleages.
2 extraer datos. Cuando tenga que esstraer info, me baso en es índice y haciendo consultas a los datastreams creando dato pariales, que seguramente es lo importante del trabajo, hacer las contultas que queremos y presentarlas, o mas bien...(redoble de tambores..) crear la herramienta para que cada doctoro/doctora pueda crear sus propias consultas.

ea, es facil el resultado pero había que llegar hasta aqui. os lo asigno, pero si estais de acuerdo, cerrais. en cuanto pueda ubir el código , os pongo las lineas donde hago este filtro, que es donde llamaba selectGeneral

**Comment by davidperezmartorell** [comment]
aqui una muestra de un unico elemento de taxon lo que hace cuando se mergea con assembleages. los datos aportan muy poco con un mergeo tan basto.
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/8990096d-3401-405e-8623-09bc633c7531)

**Comment by VeruGHub** [comment]
Hola David:
Si te he entendido bien, el índice que propones hacer es algo que ya está hecho y es id_comm, que en el esquema visual de la base de datos que te pasé tiene el nombre "Assemblage ID". 

![image](https://github.com/davidperezmartorell/forestMap/assets/29353892/837b2fd8-678a-4655-b605-99ed5220c76b) 

En la tabla de assemblages, cada id_study contiene varios id_comm (comunidad de especies forestales). En la tabla de taxones, cada id_comm tiene varias filas, que son todos los taxones registrados para esa comunidad. 
id_comm es el campo de unión entra ambas tablas. Si hacer cualquier merge con ese campo no se te duplicarán filas ni se te crearán tablas de 6 Gb.

Ya me dirás si te cuadra

**Comment by davidperezmartorell** [comment]
perfecto, si, id_comm es la variable que mas me gusta. source_id. ok.
