### ISSUE TITLE
como ver progesos en shinnyio

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#39]
Hola, para faciliaros la visualizacón dl programa sin tener que andar descargando código, os propongo que yo vaya publicando las versiones estables o con mejoras aqui

https://qm0lyl-david-perez0martorell.shinyapps.io/forestmap/

quizas podria crear un _v2 , _v3 ...ya iré viendo
Asi podeis ver el programa en acción y cuando queráis, ver las tripas como no.

Esto al ser gratuíto, tiene un número limitado de conexiones mensuales, pero a menos que le metais mucha caña, tenemos margen, miradlo cuando queráis..

**Comment by Julenasti** [comment]
Gran trabajo David!! Me encanta :)
Buena idea para que podamos ver los avances fácilmente

**Comment by VeruGHub** [comment]
Si, que guay, buen avance desde la última reunión. Gracias por facilitar la visualización así!

**Comment by davidperezmartorell** [comment]
casi es un nuevo programa :-D porque deshice el 80% pero mis conocimientos no se han reducido :-D eso es lo bueno de equivocarse :-D que aprendes mas :-D
