### ISSUE TITLE
carta a los reyes magos

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#40]
Hola Vero y Julen
creo que es buen momento para hacer la carta a los reyes.
Que os parece si escribis aqui las cosicas que os gustaría que haga el programa. Pedidlo a los reyes magos, asi lo decimos en infomrática cuando queremos hacer una lisa de deseos que pueda hacer nuestro programa y luego ir filtrandoos.
A veces cosas que nos parecen imposibles esttan ahi al lado y viceversa, pero es una herramienta para asentarlo y una vez ahi, caminar hacia esas metas.
Dedicadle un ratito, dejaros llevar, pedid a los reyes magos.

**Comment by Julenasti** [comment]
jajaja, creo que para esto, para el #37 y las otras dudas que están por resolver nos vendría bien una reunión. Por mi la semana que viene mejor

**Comment by VeruGHub** [comment]
jajajaja mi carta a los reyes es que tu, @davidperezmartorell, pienses una propuesta con lo que quieres que haga la app, basado en lo que sabes de restauración de bosques y lo que conoces la base de datos, y **antes de ponerte a programar**, nos la cuentes el próximo día en la reunión

**Comment by davidperezmartorell** [comment]
pues...sinceramente....no me considero un experto porque no he hecho biología y demas, pero si he hecho un master y algo he aprendido de la biodiversidad,ademas de lo que he leído por mi cuenta. Asi que...
me gusta 
1) por la ocnfiamza que me das
2) por la libertd que me das
y eso es lo mejor que me puede dar alguien. me hace sentir (momento romántico) querido amado, apreciado, respetado.
gracias, espero estar a la altura de lo que queréis.
Yo...mi deseo con este mapa es
1)dar herramientas a otros restauradores en cuando a la info que tenemos(limitada)
2)entender con los datos que tenemos que disrupciones y restauraciones han sido mejoras, peores, lentas rápidas, que condisiones hacen que se reupere mejor o peor, que asociación de especies.
Creo que cuando haga los mapas...tendré que dedicar un tiempo a la investigación de estas especies(que conozco poco) y como se asocian. esto me emociona tambien. Nos explicaron como se dispersan semillas, las relaciones entre especies y las sucesiones de las capas verticales, la madurez de los bosques (que no son todos los ecosisemas), pero nos interesan los bosques.
Quizas me pueden faltar info de fauna...pero...ya iremos viendo.
primero mapas, luego estudiar los contenidos y ver los datos y retorcerlos y de ahi escribir el tfm con ls preguntas y conclusiones.

**Comment by VeruGHub** [comment]
El punto 1 me parece estupendo, lo desarrollaría un poco más para la reunión. ¿Qué información es útil para los restauradores y por qué? (el número de especies? la edad del bosque? la localización?) También habría que añadir en este punto a la parte de visualizar, la parte de poder descargar los datos brutos. 
El punto 2 es un poco ambicioso, básicamente es toda mi línea de investigación jajaja. En cualquier caso se pueden explorar los datos y ofrecer algunos gráficos con tendencias temporales una vez que tengamos el punto 1.

**Comment by davidperezmartorell** [comment]
objetivos planteados, cierro tarea
