### ISSUE TITLE
Como capturar info al hacer click

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#41]
Hola, me encuentro un bloqueo que no se como solucioanr.
Al hacer click en los mapas, aparece un popup con info.
Aqui es donde se define el popup
https://github.com/davidperezmartorell/forestMap/blob/30a70a860a322cbd81c819528d06eeb6e4e4443e/renderMap.R#L49C3-L49C3

Esta info quiero traermela al server() para trabajarla pero no me llega correctamente.
Esto lo hago apra escribir una tabla bajo el mapa y luego poder trabajar los contenidos.

Aqui defino la tabla
https://github.com/davidperezmartorell/forestMap/blob/30a70a860a322cbd81c819528d06eeb6e4e4443e/generateTableText.R#L7C1-L7C1

No se como enviar los datos del click de leaflet hacia el server.

Ahora a crear la tabla, coge todo el contenido de ese id_study y con ello demasiada información.

**Comment by VeruGHub** [comment]
No tengo ni idea de como es la interacción entre leaflet y el server. @Julenasti ¿tienes algún script de ejemplo donde la información que extraes de clickar en una imagen se pueda utilizar en el server? No sé si para la trini hicistéis algo parecido

**Comment by Julenasti** [comment]
Yo nunca lo he hecho con `leaflet` pero entiendo que un `observeEvent` puede funcionar: https://stackoverflow.com/questions/74393501/leaflet-in-shiny-save-click-coordinates

**Comment by davidperezmartorell** [comment]
ya lo tengo. 
la verdad es que le ha costado.
ahora subo el código, pero básicamente con el addMArkers, le dices que marcadores salen, con las variables que quieres y defines el popup.
luego al hacer click, lo capturas con un observe
esa es la teoria pero no me salía porque teniass que gregar el id_comm como variaable fuera del popup.
ya lo tengo (tras pelearme varios dias por la noche incluso de 8 a 9 :-D )
os enlazo el código y cierro esta tarea

**Comment by davidperezmartorell** [comment]
aqui es donde recoge la info
https://github.com/davidperezmartorell/forestMap/blob/b7c167b41784f54664e3ad72ec305a2801529ad4/renderMap.R#L48C10-L48C10

este en concreto es el que recoge el identificador id_comm que es el que nos interesa para luego con la info en server() poder extraer la info que queramos mergeando o lo que queramos
[        layerId = ~id_comm,  # Set layerId to a unique identifier, e.g., id_comm](https://github.com/davidperezmartorell/forestMap/blob/b7c167b41784f54664e3ad72ec305a2801529ad4/renderMap.R#L52C7-L52C7)
