### ISSUE TITLE
mostrar info traas hacer click

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#43]
Hola
al hacer click en 1 id_comm específico, se muestra una tabla con info del id_comm, otra tabla con los id_study d ese id_comm y otros relacionados.
esto lo extrae de assemgleages.
ahora quiero agregar info de taxon para cada id_comm.

quizas agregare info del id_study de taxon.
a partir de ahi veré que analisis hago, viendo primero la info que tengo delante

**Comment by davidperezmartorell** [comment]
ya extraigo los datos.
Presento los datos del id_comm clickado, y del id_study.
Respecto los datos de id-sdudy, como contienen varios id-comm relacionados, he separado los datos comunes a todos los id_comm y los datos individuales.
Este es el resultado
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/f6c2ad6d-9987-4d53-a4e5-7ef3bcd13598)
esto lo hace aqui
https://github.com/davidperezmartorell/forestMap/blob/7391b983ff3ae332be2d248bdd632932a9426c01/studyRelated.R#L28

**Comment by VeruGHub** [comment]
Yo creo que si haces click en el pin de un id_comm sólo mostraría la información de ese id_comm y la información a nivel de id_study, pero no la de los id_comms asociados.
Me parece más ordenado si hay un lugar para clickar a un nivel jerárquico superior que represente el id_study y que si das ahí te saque la información de id_study y de todos los id_comms que contiene.
