### ISSUE TITLE
Agregar daos de easyclimate en los mapas

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#44]
Agregar contenidos de easyclimate en llos mapas que apoyen la información que se extrae de assembleages y taxon

**Comment by VeruGHub** [comment]
No te recomiendo usar easyclimate porque solo está disponible para Europa!

**Comment by davidperezmartorell** [comment]
vaya....y no se puede ampliar? que pena....en fin...habrá que inventarun easyclimate del mundo

**Comment by VeruGHub** [comment]
No se puede ampliar porque parte de un mapa climático que sólo existe en Europa (lo hace algún organismo de la UE)

**Comment by davidperezmartorell** [comment]
ok, de todas maneras, lo incluiré. debe star alli conmigo, con nosotros :-D
