### ISSUE TITLE
PAPERS: leer paper de easyclimate

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#45]
todas las tareas de leer sse refiere a leer, agregar contenido al tfm, agregar info en bibliografia, aalizar contenido y incluso ver enlaces relacionados. Valorar si agregar info en forestMap. 
Como modelo, claramente necesitamos easyclimate en nuestros mapas
https://www.sciencedirect.com/science/article/abs/pii/S1364815223000130?via%3Dihub

**Comment by VeruGHub** [comment]
El paper es para que veas como se describe una pequeña app de descarga de datos (mira los apartados) y para que pienses como estructurar tu TFM. La información no se podrá incluir como te decía porque solo existe para Europa

**Comment by davidperezmartorell** [comment]
hecho
