### ISSUE TITLE
PAPERS: ρ-MtreeRing: A Graphical User Interface for X-ray Microdensity Analysis

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#46]
leer https://www.mdpi.com/1999-4907/12/10/1405

**Comment by davidperezmartorell** [comment]
creo que esta info acerca la microdensitometría no la voy a necesitar en este trabajo salvo que hayan inventarios de microdensitometría que pueda agregarlos en los datos que tengo.
¿tenemos estos inventarios?
Creo que el programa es para analizar las meustras de los árboles pero no se si tenemos inventario
@Julenasti

**Comment by Julenasti** [comment]
Es un paquete de R para contar anillos de crecimiento y demás pero esos inventarios no existen. El paper es más bien para que veas cómo escribir un tfm más metodológico como es tu caso. No para integrarlo en tu proyecto.

**Comment by davidperezmartorell** [comment]
ok, lo veo para usar como modelo tambien

**Comment by davidperezmartorell** [comment]
revisado (tiempo atras) cierro
