### ISSUE TITLE
entre los datos que se muestran denrto del gráfico quitar algunos

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#54]
quitar los disturbance que no sean clean.
data$predisturbances_clean 
data$disturbance1_age_clean
data$disturbance2_clean

**Comment by davidperezmartorell** [comment]
no me gusta como aparece. cada linea puede tener 1,2 o 3 valores y se rpresentan en cada punto en le gráfico, mirad este ejemplo
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/c3f5e468-73ec-4f10-90ab-e4c1f4181c49)

voy a poner el contenido en 1 frase, o una tabla, ya veré con ademas otros valores interesantes relacinoados a lo mismo. quitarlo es muy facil, pero en el mismo gráfico ya no me gusta, salvo que queramos poner solo 1 único valor y que se vea como cambia.

**Comment by davidperezmartorell** [comment]
dejo solo disturbance1_age_clean que me parece mas elegante el resultado. y pruebo de ponerlo asi...como creo que peude quedar bien, en otra tabla

**Comment by Julenasti** [comment]
Sí la verdad que el gráfico está un poco raro ahora. Dejaría la mínima información que te permita responder a uno de los objetivos que establezcas del tfm

**Comment by VeruGHub** [comment]
Cada línea puede tener hasta 3 valores. Estos casos son escasos y son estudios en los que no se define bien el tipo de pre-perturbación, perturbación o post-perturbación y no sabes con seguridad qué ha pasado en las parcelas de entre las opciones que aparecen. De todos modos me parece bien quitarlo.
A mi el gráfico sólo con los puntos y los valores de riqueza (aunque lo llamaría nº de taxones) me gusta aunque sea sencillo.

**Comment by davidperezmartorell** [comment]
si, me quedo con age, richness, y en el color el stage. 
valores de riqueza (aunque lo llamaría nº de taxones)  que te refieres, a richness?
como dije, los datos los pondré en otra tabla porque hay datos que me parecen interesantes, como notes, o..no recuerdo que campos pero todos esos me parecen muy interesantes

estas en concreto:


stage <chr>, study_common_taxon <chr> historic_impact <chr>, predisturbances <chr>, disturbance1_age <chr>,
#   disturbance2 <chr>, n_disturbances <int>, current_impact <chr>, notes <chr>, priority <chr> study_common_taxon_clean <chr>, study_common_taxon_strgroup <chr>, disturbance1_age_clean <chr>, disturbance2_clean <chr>,
#   predisturbances_clean <chr>, current_impact_clean <chr>, postdisturbance <chr>, restoration <int>, protection <int>, use <chr>
lo pongo en otra tarea de mostrar una tabla...a ver si nos gusta.
lo haré con el distinct() o unique() a ver que info extraigo.
A mi me gusta tener la info, luego dresumirla, y abstraerse para ver de forma general todo, pero hay que tenerla delante.

**Comment by davidperezmartorell** [comment]
corregido. a ver si os gusta la tabla con toda la info en la misma pestaña que el gráfico. cierro eto porque ya lo vereis cuando veais la demo, no hace flta hacer nada aqui. y si hiciera falta, lo vemos en la próxima reunión

**Comment by davidperezmartorell** [comment]
hecho
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/8928814a-02db-48a0-82e3-1e85e0576a19)

**Comment by davidperezmartorell** [comment]
ya he aumentado el tamaño de los ejes y demas.
