### ISSUE TITLE
pregunta aceca máximo detalle

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#57]
Hola, me ha aparecido una dda.
En la navegación por el mapa, el maximo detalle que queremos creo recordar que es el id_study y no llegar al id_comm.
entiendo que en los gráficos tambien, que nos salgan dentro de cada estudio los id_comm, pero no quremos gráfico a nivel de id_comm.
Estos apareceran cuando estudiamos los estudios, peor el minimo detalle es el id_study, verdad?

voy a cambiar el código para que el detalle mas fino en la navegación sea id_study, a er que tal sale...

**Comment by davidperezmartorell** [comment]
si, modificado too apra que sea el máximo detalle idstudy, aunque luego en alguna tabla hago que aparezca como info complementaria id_comm

**Comment by VeruGHub** [comment]
El máximo detalle que dijimos de ver es id_study, si :)
