### ISSUE TITLE
tarea que consume tiempo

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#65]
Hola,encontré que una tarea repetitiva, consume mucho tiempo (unos segundos, quizas 10) y se puede evitar.
Es esta
assembleages <- fillCountryAccordingLatLon(assembleages)

aqui lo que hacemos es enviar el datastream assembleages para que rellene info que faltaa del pais de cada estudio
Tengo un cat que nos muestra el resultado y dice lo siguiente

Has been detected 104  registers with NA value in country column.Has been detected 0  registers with NA value in new country

Mi pregunta es: @VeruGHub ¿podriamos agregar los datos de paises NA ( o lo que sea) para no tener que calcularlo cada vez que entramos?. Sería modificar el assembleages las columnas que son NA

**Comment by VeruGHub** [comment]
Claro. Lo suyo es hacerlo una única vez. A mi el campo de país no me servía para mucho pero tu lo necesitabas para obtener la capital y sus coordenadas y entonces representar los puntitos en las capitales de cada país. Confirmamelo tú, pero las coordenadas de las capitales ya no se utilizan para nada y se puede quitar... ¿no?

**Comment by davidperezmartorell** [comment]
resuelto. los problemas principales era que trabajaba los datos cada vez que cargaba, y resolvimos que grabe el archivo con los datos alli
Por ejemplo para agregar paises, o citation.
Tambien hago menos veces los merges para los gráficos. Con 1 merge que incluso ahora carga de 1 archivo, es suficiente.
Ahora va mas rápido.
Seguramente se puede optimizar mas aun el código, pero necesitaría de un programa que mide los tiempos de las funciones y esto lo dejaría para mas adelante porque ahora ya carga rápido
