### ISSUE TITLE
divission de datos al hacer zoom

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#66]
Hoa pareja. al trabajar en lo mapas leaflet con id_study, me aparecen los datos diferntes a cuando los juntaba por id_comm
aqui los datos. que os parece? 
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/75329292-d1ba-42ff-88d0-af7534ce9a83)

subo la version al shinny para que podais [navegar](https://qm0lyl-david-perez0martorell.shinyapps.io/forestmap/). https://qm0lyl-david-perez0martorell.shinyapps.io/forestmap/
los datos de las tablas ya estan actualizados...pero.... hay que verlos a ver si estan bien.
Tenemos que ver si el tema que dijimos de centroides lo hemo solucionado con esto

**Comment by davidperezmartorell** [comment]
Mirad esto, lo podeis ver en el piloto aqui
https://qm0lyl-david-perez0martorell.shinyapps.io/forestmap/

en Galicia habia 1 sitio con 50 puntos creo recordar. cuando lo hemos separado por id_study se dividen pero no se seguro como lo divide, aqui la imagen d Galicia
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/d7b8056f-5416-4f0d-8868-0fe4231b6450)

este es uno de los puntos
ID = PR_Calvino-Cancela et al. 2012_Herbs & Ferns_IntEuc4_NA
study_id = PR_Calvino-Cancela et al. 2012_Herbs & Ferns

pero para ese study_id hay 25 ID con nombres comunes de id_study, misma lat y long pero diferentes sites
IntEuc[12345], MatEuc[12345], NatFor[12345], PineP[12345], YngEuc[12345]

La pregunta es @VeruGHub ¿como puedo identificar a los estudios "hermanos", o sea los 5 IntEuc[12345]. Quias tengo que hacer el invento de buscar id_study que contenga IntEuc quitando el número pero esto puede generar errores.

Si quereis, podemos verlo  en la proxima reunión.

**Comment by VeruGHub** [comment]
Dentro de cada "citation" hay uno o varios "id_study" con varios "id_comm". El campo "site" que es el que define id_comm (es decir, cada id_comm está hecho en un site diferente dentro de cada id_study), pero puede ocurrir que 2 estudios diferentes (dos id_study diferentes) estén hecho en los mismos sites, como es el caso porque se han muestreado diferentes organismos:

Citation = Calvino-Cancela et al. 2012
id_studies = PR_Calvino-Cancela et al. 2012_**Herbs & Ferns** / PR_Calvino-Cancela et al. 2012_**Shrubs & Trees**
sites = IntEuc[1,2,3,4,5], MatEuc[1,2,3,4,5], NatFor[1,2,3,4,5], PineP[1,2,3,4,5], YngEuc[1,2,3,4,5] (25 en total)

id_comms = 2 studies x 25 sites = 50 id_comms

Si los sites tienen las mismas coordenadas, las tears no deben salir en coordenadas diferentes como pasa ahora. Tiene que diferenciarse claramente cuando el tear marca la coordenada exacta que cuando aparece representado en un sitio random por desdoblamiento porque si no puede crear confusión al usuario. Quizás en este segundo caso haya que hacer unas rayas negras que unan el tear a la coordenada exacta o que no se desdoble directamente, si no que simplemente al clickar te salga toda la información de esa localización espacial

**Comment by VeruGHub** [comment]
Respecto al primer comentario: en la reunión anterior dijimos que hubiera un centroide por id_study, pero no es lo que pasa ahora. Al hacer zoom se sigue desdoblando en unidades más pequeñas

**Comment by davidperezmartorell** [comment]
claro...estoy mirando los datos del Calvino por ejemplo y veo lo siguiente
citation=Calvino-Cancela et al. 2012
a partir de ahi divide segun site : IntEuc1,IntEuc2,IntEuc3,IntEuc4,IntEuc5,MatEuc1,MatEuc2,MatEuc3,MatEuc4,MatEuc5, NatFor1,NatFor2,NatFor3,NatFor4,NatFor5,PineP1,PineP2,PineP3,PineP4,PineP5,YngEuc1,YngEuc2,YngEuc3,YngEuc4,YngEuc5,

cada uno de ellos tiene la misma lat y lon para la siguiente division de study Herbs & Ferns y Shrubs & Trees

Esto para el Calvino, para el resto puede ser diferente.


...sigo mirando....

**Comment by davidperezmartorell** [comment]
vale, la maxima granularidad es id_study.
Ya el id_comm no aparece. a ver que nos aprece asi.
PD: subí la version y puse una falta ortografica...fatal ...puse "arribe" en lugar de "arrive" . pecaa minuta...pero me molestan esos errores.

**Comment by davidperezmartorell** [comment]
resuelto
