### ISSUE TITLE
documentos para tfm y practicas

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#74]
Instrucciones acerc lo que se debepresentar para practics 1 y 2. Envío el correo
[convocatoria PExt y TFM_febrero_2024_SR.docx](https://github.com/davidperezmartorell/forestMap/files/13994221/convocatoria.PExt.y.TFM_febrero_2024_SR.docx)
Básicamente es un excel que enviare en cuanto acabe de rellenar este issue.
Tenemos que crear 2 documentos
o	Informe de Evaluación de las actividades realizadas durante las Prácticas Externas, firmados por el director de las mismas, de la institución en la que se hayan realizado; el modelo está disponible en https://masterrestecos.web.uah.es/materias.html. Será enviado por el director de las prácticas al correo electrónico de Salvador Rebollo de la Torre ([salvador.rebollo@uah.es](mailto:salvador.rebollo@uah.es)) y a José Luis Jociles Noguero ([master.restauracion@uah.es](mailto:master.restauracion@uah.es)), indicando en el asunto del mensaje “Informe Evaluación Prácticas Externas_Nombre del Estudiante_Máster Restauración”. Por favor, indicad en el título de este informe si son Prácticas Externas I o II.
o	Cuestionario de satisfacción del estudiante, que deberá enviarlo el estudiante firmado y por correo electrónico a las mismas direcciones indicadas arriba, indicando en el asunto del mensaje 
o	“Cuestionario de Satisfacción Prácticas Externas_Nombre del Estudiante_Máster Restauración”. El modelo está disponible en https://masterrestecos.web.uah.es/materias.html.

Aqui el excel que envío ahora acerca las prácticas. Para el TFM es lo mismo pero con otras celdas rellenas
[PExtI_II y TFM_DAVID_PEREZ_MARTORELL_feb2024.xls](https://github.com/davidperezmartorell/forestMap/files/13994405/PExtI_II.y.TFM_DAVID_PEREZ_MARTORELL_feb2024.xls)

**Comment by VeruGHub** [comment]
Vale, gracias David! Es lo mismo que hice la otra vez, pero la otra vez me enviaron un correo avisándome y ahora no

**Comment by davidperezmartorell** [comment]
cierro tarea. todo completo.  a ver que dicen los del master
