### ISSUE TITLE
Taabla citacion y taxon

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#75]
Cuando Puedas Vero, enviame la tabla citacion y el taxon completo.
gracias

**Comment by davidperezmartorell** [comment]
si, dime como hacerlo. me gustaría que cada estudio tenga su enlace al paper.
o lo hablamos en una reunion, o creas una isssue y lo explicas o lo que me digas.

**Comment by VeruGHub** [comment]
Te mandé un correo a tu gmail la última vez que hablamos ¿lo has recibido?

**Comment by davidperezmartorell** [comment]
sisi, lo he trabajado. hay un programa en R que te dice los DOIS's y con ello puedo etirar del hilo.
lastima que el progrmita no te extrae el autor y el correo. endre que hacerlo a mano,

**Comment by davidperezmartorell** [comment]
resuelto tema tabla citation. te la envío por correo
