### ISSUE TITLE
agregar boton dentro del plot para ver stage

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#83]
queremos que en el mapa aparezca un boton donde se pueda ver el stage y filtrar los resultado segun la combinacion de stage
puede ser recuperandose, referencia o perturbado.

**Comment by davidperezmartorell** [comment]
he agregado el boton dsegun estado stage, pero no nos aporta la experiencia que nos interesa porque no distingue a simple vista los stage, debes clickar y leer la info.
La alternativa es que en lugar de lágrimas (tear) comunes, hacer cídculos en funcion de stage y una leyenda.
a ver que os parece. lo vemos en la siguiente reunión.
subo esta versión

**Comment by VeruGHub** [comment]
David, ¿como tienes para juntarnos este viernes por la tarde (sobre las 3 o así) y ver los avances? @Julenasti ¿tu como lo tienes?

**Comment by davidperezmartorell** [comment]
sisi, esta bien, pero tengo todo un poco empantanado :-D bueno, otraas veces me ha ocurrido lo mismo que no he puesto orden al código hasta el ultimo momento.
reordenar los datos de taxon_clean me ha costado bastante, quiero decir,, agregar para todos lo taxones su kingdom, genus..etc...
al final, de los 300mil, hay unos...1000 quizas que he tenido que poner other. un 0,3% me decian que eran bacterias o incluso alguna especie de insecto y eso seguro que esta mal. ademas de los unknown.

**Comment by davidperezmartorell** [comment]
y para quedar, si, esta bien, el viernes 09/02/2024 mismo a las 15:00 si no me bloquean con entrevistas que esta la cosa muy caliente.

**Comment by Julenasti** [comment]
Por mi el viernes bien también!

**Comment by davidperezmartorell** [comment]
vimos que el disturbance, como va cambiando en el tiempo, solo mostraría un unico estado. asi que descartamos tener 2 variables en mapa principal.
Al final acordamos un valor que combine los posibles cambios de estado de los estudios que tras filtro, sone stos
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/9be50743-3397-4709-81d8-ef125c2ab6bc)

Asi, que solo mostramos esto.

**Comment by VeruGHub** [comment]
Perfecto :)

**Comment by davidperezmartorell** [comment]
Vero, este mensaje no esta sincronizado. Julen dijo OK , pero su correo es
del 6 de febrero.
Si os parece podemos quedar este viernes.

**Comment by Julenasti** [comment]
Por mi el viernes bien David! Vero está de excursión con los estudiantes por lo que no sé si podrá contestar. Creo que vuelve el jueves. Esperamos a su respuesta, a ver si puede

**Comment by davidperezmartorell** [comment]
Ok. El viernes salgo a las 15. Podemos quedar a las 17

**Comment by VeruGHub** [comment]
Hola: yo hoy no puedo ya, disculpad que haya tardado en contestar. El mensaje de este hilo sobre quedar era de hace un montón y ya quedamos...
¿Podemos fijar otro día de la semna que viene?

**Comment by davidperezmartorell** [comment]
Por mí, bien. si quereis el próximo viernes.
Ya he finalizado todo lo que dijimos de hacer y ando buscando gráficos que
me expliquen el origen del universo :-D :-D
ya estoy empezando a documentar poco a poco.

**Comment by Julenasti** [comment]
Hola! Genial David, con ganas de verlo :) 
Yo este viernes por la tarde no puedo. Sino a partir de las 18/19 podría los demás días excepto el miércoles

**Comment by Julenasti** [comment]
Perfecto! Cuando mejor os vaya. Quizás mañana mejor?

**Comment by VeruGHub** [comment]
Hola! Yo puedo los dos días. Lo dejamos para mañana a las 19. Gracias!
