### ISSUE TITLE
datos posiblemente incorrectos de Calvino

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#87]
Hola, estoy analizando os datos de Calvino. veo esto
aqui datos de asembleages
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/8fa1e0e5-280c-4b30-8796-343a26842276)
aqui datos de taxon_clean junto los que extraigo de la tabla anexo de Calvino
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/3b9d4fe2-721c-4b5b-b1c0-c5ef561ba043)
no se como relacionar los datos, si has agregado algun calculo para enviarlos de la tabla de Calvino a nuestra tabla

**Comment by davidperezmartorell** [comment]
para este otro (Webb and Sah 2003) , parece que si cuadran mas los datos , o sea, que estan los mismos numeros y segun el paper es el que me cuadra mas porque de cultivos de arbol de sal hicieron alternativas tras talar. plantar mas arbol de sal, plantar eucalipto o no hacer nada
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/fe56ecb0-e5f5-4bdb-a16b-39175ad160d6)

**Comment by VeruGHub** [comment]
Hola David! como te dije los datos de Calvinho parecía que estaban mal y es probablemente un error al leerlo en R y/o en excel o algo así. Dejame checkearlo en los datos originales y te digo algo
