### ISSUE TITLE
los datos latitud y longitud estan mal

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#93]
Hay que darles formatos unificados.

**Comment by davidperezmartorell** [comment]
que son estos valores de latitud, longitud?
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/piura/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/piura/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


exact_lat | exact_long
-- | --
-993.916.666.666.667 | -678.652.777.777.778
-993.694.444.444.444 | -678.472.222.222.222
-993.555.555.555.556 | -678.747.222.222.222
-811.771.666.667 | 157.131.383.333
-808.671.666.667 | 157.146.733.333
-807.553.333.333 | 1.571.486
-806.818.333.333 | 157.142.016.667
-804.766.666.667 | 15.714.615
-804.341.666.667 | 15.716.335
-804.016.666.667 | 157.124.733.333
-803.801.666.667 | 157.122.316.667
-802.903.333.333 | 157.004
-802.848.333.333 | 15.698.095
-802.816.666.667 | 15.714.175
-802.381.666.667 | 157.133.216.667
-802.353.333.333 | 157.108.733.333
-801.438.333.333 | 156.956.016.667
-801.096.666.667 | 1.571.065
-800.938.333.333 | 156.958.466.667
-798.896.666.667 | 15.709.295
-798.323.333.333 | 156.952.516.667
-798.253.333.333 | 156.966.266.667
-796.596.666.667 | 156.958.666.667
-796.021.666.667 | 156.996.033.333
-789.326.666.667 | 15.712.125
-787.703.333.333 | 15.706.795
-785.711.666.667 | 157.072.216.667
-397.504.444.444 | -790.787.861.111
-397.488.333.333 | -790.751.805.556



</body>

</html>

**Comment by davidperezmartorell** [comment]
esto tenemos que seguir mirndolo. he ido a una ersion anterior par que no me de error.  cuando ejecuto la funcion fillCountryAccordingLatLon.R de alguna manera, arregla los datos, seguramente porque les pone un valor correcto al ppasarlo a sf o algo asi. si evito el programa me da error de lat y lon. por ahora lo dejo asi y lo corrijo en cuanto pueda porque no quiero que pase el programa por rellenar pais cada vez que se ejecuta

**Comment by davidperezmartorell** [comment]
corregido. al final, he tnido que mirar los datos a mano. habia seguramente un baile de comas, puntos, decimales, valores con 2 digitos, muchos mas digitos. tambien en formatos grados. grados decimales o grados-minutos-segundos.
he unificado y listos.
al final, como cada estudio hace una media de las comunidades, no precisamos los datos conretos de cada comunidad y si lo necesitamos, deberiamos ir a los estudios y extraerllos datos de manea uniforme.
arreglado y propuesta de mejora en un futuro, fuera del alcance de este TFM

**Comment by VeruGHub** [comment]
Aquí tienes el issue donde hablabas de la corrección de las coordenadas para cuando lo repases :)

**Comment by davidperezmartorell** [comment]
si, esto fue causado al transformar datos desde excel, porque en varia ocasiones movi los datos de R a Excel para combinar columnas y demas. Al final lo hice todo en R sin pasar por excel.
De todas formas, tambien busqué como decirle a excel que al importar los . (puntos) identifican los decimales, pero ya no lo uso.
Se puede cerrar, ya no tengo problemas con esto

**Comment by davidperezmartorell** [comment]
nada, a mano, solo en algun caso puntual de quitar un ; o algo asi, pero poco. si hubieran muchos haría un filtro y almacenaría el csv nuevamente como hive al buscar paises o cosas asi
