### ISSUE TITLE
Calvino me da problemas :-D

### ISSUE THREAD

**Issue by davidperezmartorell** [davidperezmartorell/forestMap#97]
Hola, veo que curiosamente, los datos de Calvino no me cusdran. quizas es el studio excepcionn.
mi sospecha es que los daos que vienen del paper son incorrectos.
Aqui te muestro los datos del paper de un ejemplo y los datos que llegan a R tras importar. Te lo muestro en exxel porque se ve mejor, pero es el mismo valor
Por otro lado, en el estudio de Calvino, en el anexo, da unos datos por comunidad, pero en el anexo no hace referencia a los años de la toma de datos.
¿es posible que realizaras algun tipo de calculo relacionando inventario con tamaño de la muestra o algo asi?
![image](https://github.com/davidperezmartorell/forestMap/assets/106980919/51eb6395-c34f-4e01-b7b7-6c0f6b3c1e84)

**Comment by VeruGHub** [comment]
Me da error al descargar la base de datos actualizada de Predicts. Parece que tienen el archivo corrompido. He escrito a los autores del artículo a ver si nos pueden pasar los datos correctos. Mientras tanto, como no afecta a los gráficos de resumen, no te preocupes. 
Si me contestan con los datos correctos los podemos actualizarlos en nuestra base de datos y si no, me limitaría a transformar la matriz a una de presencias/ausencias, que eso sabemos que está bien.

**Comment by davidperezmartorell** [comment]
resuelto, al final medimos por presencia/ ausnecia ignorando el valor que obtenemos de riqueza o abundancia como numero
